### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by madhon** [linked-data-dotnet/json-ld.net#11]
Would be nice if there was examples of usage, e.g. standalone or part of aspi.net webpi

**Comment by asbjornu** [comment]
I think [Nancy.Rdf](/wikibus/Nancy.Rdf) makes a good example of how json-ld.net can be implemented.

**Comment by tpluscode** [comment]
Thanks. I'd also look at [JsonLD.Entities](https://github.com/wikibus/JsonLD.Entities)

**Comment by DavidDeSloovere** [comment]
It's great that this library is on nuget and github. But without some guidance or examples, how will people actually use this instead of looking for another library that have examples?

**Comment by emgarten** [comment]
Any and all doc PRs for this would be greatly appreciated :smile:

**Comment by colin-young** [comment]
As a start, it would be helpful to have a general hint about what things one can expect to do with this library. I know from another thread here that it's not for serializing POCOs to JSON-LD. So of the approximately infinity other things I can do with a computer program, which ones will this library help with? My understanding is that it was created to help with NuGet returning JSON-LD data, so obviously it must be of some help in generating JSON-LD, but how?

The problem with [JsonLD.Entities](https://github.com/wikibus/JsonLD.Entities) and [Nancy.Rdf](https://github.com/wikibus/Nancy.Rdf), while I'm sure they are excellent libraries, is that at the moment almost all of my work around learning JSON-LD is being done in .Net Core on OS X, so the fact that they depend on paket and Fody (for starters -- both also have several other dependencies that are not supported on Core) makes that route a non-starter for me.

Something as simple as "given the following JSON-LD, to read it and access the data..." and "to produce JSON-LD in the following format..." would be helpful. Since I'm going to have to learn this anyway, I'm happy to produce a doc PR, but I know just enough about JSON-LD to be dangerous so I'm going to need somebody to get me pointed in the right direction first.

**Comment by tpluscode** [comment]
@colin-young json-ld.net also doesn't work on Core, does it?

**Comment by colin-young** [comment]
According to [Introducing .Net Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/), Core implements .Net Standard 1.6, and according to [NuGet](https://www.nuget.org/packages/json-ld.net/), json-ld.net is supported on .Net Standard 1.3, so it should work. I _know_ I've compiled with a reference to json-ld.net, but I'm not 100% sure I've run it thought. I will confirm this evening that I can run the unit tests on OS X.

**Comment by emgarten** [comment]
@tpluscode json-ld.net supports netstandard1.3  

https://github.com/NuGet/json-ld.net/blob/353e89eafdba1bee481925ee710d2407a24c641a/src/json-ld.net/project.json#L32

**Comment by nicholastic** [comment]
OK, but how are we supposed to use this library with no examples? Why wouldn't you write a quick example after all the effort you've gone to? Don't you want people to use this software? You're listed on https://json-ld.org/, but with no examples there's no point wasting time on this.

**Comment by nicholastic** [comment]
I notice there aren't any Job objects, for example, in the code. Do we have to make our own objects? How do we use this library???  Why write an entire library and then not one even sentence on how to use it? So weird. I'm using MXTires.Microdata instead.

**Comment by nicholastic** [comment]
What's the point of publishing a library if it has no docs or examples? It doesn't take long relative to writing the library. Would be good to have a quick example.

**Comment by madhon** [comment]
> What's the point of publishing a library if it has no docs or examples? It doesn't take long relative to writing the library. Would be good to have a quick example.

Exactly, and the owner enabling the github statebot to kill off issues hes ignoring doesn't inspire confidence either.

**Comment by asbjornu** [comment]
I take responsibility of enabling @stalebot. Having issues open since 2016 doesn't help anyone. This repository is maintained on a volunteer, private basis by the community.

I'm not a JSON-LD expert, so I can't assist with solving this issue. But I've got experience with maintaining open source repositories, which is why I agreed to help maintain this one. If you have ideas on how to maintain it better, then please come forward and help out. Pull requests are welcome.

**Comment by madhon** [comment]
> I take responsibility of enabling @stalebot. Having issues open since 2016 doesn't help anyone. This repository is maintained on a volunteer, private basis by the community.
> 
> I'm not a JSON-LD expert, so I can't assist with solving this issue. But I've got experience with maintaining open source repositories, which is why I agreed to help maintain this one. If you have ideas on how to maintain it better, then please come forward and help out. Pull requests are welcome.

This issue is about documentation on how to use the library, not the code itself , surely that's a basic thing to add in for you, otherwise how can you maintain it yourself, as you would not know how to use it ?

**Comment by asbjornu** [comment]
> otherwise how can you maintain it yourself, as you would not know how to use it ?

There's more to maintaining an open source repository than to write the code that resides within it. Are the following uses of `json-ld.net` helpful? If so, I can look into adding something like it the documentation.

https://github.com/wikibus/JsonLD.Entities/blob/master/src/JsonLD.Entities/EntitySerializer.cs#L89-L106

https://github.com/wikibus/JsonLD.Entities/blob/master/src/JsonLD.Entities/EntitySerializer.cs#L124-L139

**Comment by goofballLogic** [comment]
I'll put a bit of work into this. As a minimal starting point we could port and flesh out the examples from https://github.com/digitalbazaar/jsonld.js/blob/master/README.md

**Comment by goofballLogic** [comment]
Somewhat related for those who are interested - which versions of .NET should we support (in both code and documentation)? Contribute to the discussion in #59 . Part of https://github.com/linked-data-dotnet/json-ld.net/milestone/1 due by August 1st.

**Comment by goofballLogic** [comment]
Also added https://github.com/linked-data-dotnet/json-ld.net-Demo which contains samples for inclusion in the README of this repo
