### ISSUE TITLE
Stewardship of this repository

### ISSUE THREAD

**Issue by asbjornu** [linked-data-dotnet/json-ld.net#26]
It has been discussed for a while now how this repository is being maintained, as exemplified by @goofballLogic in https://github.com/NuGet/json-ld.net/pull/24#issuecomment-377193661. The NuGet team seems to have run out of active maintainers and pull requests remain open for months and issues open for years without any attention.

[A discussion on the public-linked-json mailing list](https://lists.w3.org/Archives/Public/public-linked-json/2018Apr/0006.html) brings forth different options for how the community can contribute to bring the stewardship of this repository back on track so the .NET community can have a well maintained and up to date JSON-LD implementation.

Here are some suggestions for how to move forward:

- Set up a semi-automatic Sharpen-conversion from [jsonld-java](https://github.com/jsonld-java/jsonld-java) that will be repeated every now and then.
- Add more maintainers to this repository.
- Move the repository to a different organization.

We would love to get some input from @emgarten, @sblom or anyone else that have ownership status of this repository at the moment, because the current state of affairs is unfortunate.

**Comment by emgarten** [comment]
@skofman1 @rrelyea  would you help make a decision on this?

I would really like to see this project move forward, and these look like great suggestions for allowing that to happen.

NuGet gallery still uses this library as far as I know, but the current implementation works fine for them and there has not been any work done by the NuGet team in quite some time. My guess is that consumers of nuget.org aren't reading it as json-ld, so even if things are incorrect, no one is reporting it. Which is why this isn't being updated.

The issues and PRs coming in for this repository require a lot of technical expertise on RDF and json-ld. It takes a effort to determine if a PR is actually the correct fix for an issue just based on the json-ld output. @sblom, @johnataylor, and myself who previously worked on this library are no longer on the NuGet team which has made this more difficult.

**Comment by skofman1** [comment]
@asbjornu , @goofballLogic thanks for bringing this to our attention. I will work with the team to determine the best course of action.

**Comment by gkellogg** [comment]
Note that [jsonld-java](https://github.com/jsonld-java/jsonld-java) is, itself, only [lightly maintained](https://github.com/w3c-ccg/did-spec/issues/9#issuecomment-366808393). Other implementations are updating with features from the [JSON-LD 1.1 CG Spec](https://json-ld.org/spec/latest/json-ld/), and a new [JSON-LD Working Group is being chartered](https://www.w3.org/2018/03/jsonld-wg-charter.html), so if developers are interested in moving this version forward, it would be shame if they are handicapped by less progress on the jsonld-java side.

There is no substitute for active and interested maintainers.

**Comment by danbri** [comment]
+ Tom Marsh (@tmarshbing) who coordinates Microsoft (incl. Bing's) participation in Schema.org

**Comment by skofman1** [comment]
Thanks everyone, for you enthusiasm in making contributions or taking this repository forward.

After a conversation internal to the NuGet team, we realized that we did not have any expertise left on the team who can successfully maintain this repository and either contribute directly to it or manage our community contributions. While NuGet.org has a dependency on this package, we have not really required any code changes for many years now, and we don’t see this changing.

In order to take this repository forward as expressed by the community, we are proposing the following:
•	We will work with anyone in the community who has a strong interest in this code-base to transfer ownership of the repository to you (or a set of you).
•	We will transfer the repository from being under the NuGet organization to another organization that the owners decide.
•	We will also transfer ownership of the packages on NuGet.org to another account that the owners decide.

There will be no changes that the NuGet team will propose the licensing terms, code of conduct, and such and we will defer all future decisions regarding the code in this repository to its new owners. The transfer of ownership will be as-is.

Please let us know your thoughts about this plan. If there is general consensus, we will work on the next steps to identify a set of future owners for this repository.

**Comment by goofballLogic** [comment]
I have a strong interest in this code base.

I'll mention this on the public-linked-json W3 mailing list to see if others are interested, and to encourage brainstorming ideas about where best to host the repository moving forward.

Note that I personally would have no objections to maintaining the repository within the Nuget organisation as the Nuget name lends some authority to the package. However, I can understand you may not wish to have outsiders maintaining a package in your name.

**Comment by tpluscode** [comment]
> have outsiders maintaining a package in your name

Isn't that the essence of open source collaboration? 🙃 

As long as there is an active maintainer who would take care of code quality and coverage I think it's a good choice to stay under the NuGet organisation.

**Comment by goofballLogic** [comment]
Those who responded on the public-linked-json W3 mailing list agree that it would be good for the repo to remain part of the Nuget organisation. This would mean:

1. Creating a repo-specific group for maintainers with administrative privileges over this repository
2. Specifying the members of this group as "Package Owners" for purposes of publishing to Nuget

Is this something that you are open to @skofman1 ?

**Comment by goofballLogic** [comment]
@tmarshbing - as mentioned above to @skofman1 we think it would be good for this library's profile to remain within the NuGet organisation. Is it possible to set up a group of maintainers (I am volunteering) with administrative rights over just this repo, and the ability to publish to NuGet ?

**Comment by skofman1** [comment]
@goofballLogic , @tpluscode , 

> As long as there is an active maintainer who would take care of code quality and coverage I think it's a good choice to stay under the NuGet organisation.

There's no one in the NuGet team that can maintain the repository, since, as was mentioned before, we have no knowledge left on the team on this code base. We can't lend our name to a code base we can't guarantee the quality off, hence, to allow open source collaboration, the repository **must** move out of NuGet's GitHub organization.

**Comment by goofballLogic** [comment]
I suggest that the repo is moved to the https://github.com/linked-data-dotnet organisation which I have set up as a (temporary?) location so we can start fixing things. @tpluscode @asbjornu @gkellogg @tmarshbing - anyone wish to propose otherwise?

**Comment by asbjornu** [comment]
@goofballLogic: As the repository can be moved from @linked-data-dotnet whenever we find a better home for it, I give it my two thumbs up. 👍

**Comment by tpluscode** [comment]
I was going to propose https://github.com/json-ld but I see that it doesn't really host any implementations. I guess I too agree with @goofballLogic. The only other org I found is https://github.com/RDF-Utilities-dotnet which doesn't offer much more visibility either.

**Comment by tpluscode** [comment]
HA! It did cross my mind but I don't know what @kal would say given recent effort for dotNetRDF's own JSON-LD support 🙃

**Comment by kal** [comment]
Thanks @tpluscode! As much as I would like to support this code base too I think I have my hands full with dotNetRDF :-)

**Comment by asbjornu** [comment]
@goofballLogic: Sure. We can always rejuggle ownership and administration after the transfer is complete.

**Comment by skofman1** [comment]
Sounds good @goofballLogic !
Will handle the transfers next week.

**Comment by danbri** [comment]
This sounds sensible. We could also point to the project from Schema.org
somewhere if that helps. Better JSON-LD support in every language is
certainly something in line with our efforts...

**Comment by skofman1** [comment]
@goofballLogic , I need permissions to create repositories in  https://github.com/linked-data-dotnet in order to perform the transfer.

**Comment by goofballLogic** [comment]
Just invited you 

⁣Sent from TypeApp ​

**Comment by skofman1** [comment]
Repo transfer completed 😄 
Regarding the package on nuget.org, I recommend that you create an organization to own the package, and add all other contributors to this org. Documentation here: https://docs.microsoft.com/en-us/nuget/reference/organizations-on-nuget-org

**Comment by goofballLogic** [comment]
Thanks @skofman1 I have set up https://www.nuget.org/profiles/linked-data-dotnet for this purpose

**Comment by skofman1** [comment]
@goofballLogic , ownership request sent. After you accept I will remove 'nuget' as an owner.

**Comment by veikkoeeva** [comment]
In my humble opinion, a general purpose .NET Standard 2.0 compatible, easy to digest JSON-LD 1.1 library is difficult to find and considering the importance, I find it a bit odd there isn't one baked into the official framework. Just in case, I'd like to page @RehanSaeed of https://github.com/RehanSaeed/Schema.NET. It'd would be great to see efforts pooled, unfortunately for the time being I lack the expertice to contribute much anything. It's the knowledge-available time gap.

**Comment by goofballLogic** [comment]
Plans exist to try and update the library by the end of next month. However, this will likely be just getting the 1.0 version up to date.

Once updated, the upgrade path to 1.1 should be much simpler and PRs will be welcome.
