### ISSUE TITLE
Can Context generation be automated using POCO classes with attributes?

### ISSUE THREAD

**Issue by object** [linked-data-dotnet/json-ld.net#3]
I am just thinking loud now, but to me it seems that context can be generated from plain C# classes annotated with custom attributes. Is this something that can be useful for this library?

**Comment by asbjornu** [comment]
@tpluscode @object Did you reach some sort of conclusion on how to unite the work so we can all contribute to a single library with attributes we can decorate our serialization entities with?

**Comment by markchipman** [comment]
I'd like to know where this is going also... The example of what @object showed us makes a lot of sense.  Would be great to have one library that can use POCOs and rely on schema.org's data definitions.  I'm thinking of taking this idea one step further for the masses by giving ANY user who doesn't know a thing about schema.org or JSON-LD a way of storing their content (whether it be an event, product, etc.), storing it in a datastore (mongo, sqlserver, redis, etc.) and spitting out pre-formatted HTML text nuggets that they can dynamically embed into their webpages easily via JQuery and AJAX.  I know that goes way beyond what json-ld provides, but the rendering of the final view is helpful for many I believe.

**Comment by tpluscode** [comment]
You may be interested in the library I started - [wikibus/JsonLD.Entities](/wikibus/JsonLD.Entities). It certainly shares some similarities with what @object illustrated above. There's a documentation link in the readme. Maybe I should emphasize it more...

For quick-and-dirty JSON-LD serialization there is a context helper, which simply applies a given namespace, like schema.org, to you object structure. 

```
public class Person
{
    public string GivenName { get; set; }

    public string LastName { get; set; }

    public static JObject Context { get; } => new VocabContext<Person>("http://schema.org");
}
```

When serialized, that would produce a JSON like

```
{
  "@context": {
    "givenName": "http://schema.org/givenName",
    "lastName": "http://schema.org/lastName"
  },
  "givenName": "Tomasz",
  "lastName": "Pluskiewicz"
}
```

**Comment by tpluscode** [comment]
For the HTML part you may like the idea that I'm experimenting with using Web Components. 

The idea is that you can package HTML template for given data (for example for a matching `@type`

```
<!-- template for your data @type = schema:Person -->
<template is="ags-type-template"
          type="http://schema.org/Person" as="person"
          compact-with='{ "@vocab": "http://schema.org/" }'>
    <!-- your-html goes here and supports data binding -->
    <div>
        {{person.givenName}}
    </div>
</template>

<!-- this will render your data -->
<ags-view id="view"></ags-view>

<!-- to render, set the property on ags-view -->
<script>
  document.getElementById('view').object = {
    "http://schema.org/givenName": "Tomasz",
    "http://schema.org/lastName": "Pluskiewicz"
  };
</script>
```

You can see my [blog posting](http://t-code.pl/blog/2016/04/hypermedia-driven-ui/) for a more detailed example. Note though that the elements' names have changed since. The code is at [wikibus/augeas](/wikibus/augeas). Unfortunately no docs at this point yet.

**Comment by tpluscode** [comment]
@markchipman Do these ideas somewhat resonate with your needs?

**Comment by markchipman** [comment]
@tpluscode ... thanks for getting back to me.  

Hmmm, I'm not quite sure how it might fit in.  I want to investigate wikibus/JsonLD.Entities more, but as far as the html rendering goes, I'm not sure what I want to do.  I tested the execution of the templating mechanism that you linked to in Plunker, and although I like the outcome, the performance was rather sluggish... and that was a small data-set... how does it perform with something rather complex and large?

What I am looking at is having a solution where the JSON-LD is auto-generated based off of the server-side POCO model.

I should regress abit and explain what I'm really going after... awhile ago I purchased the domain names usedotnetwithschema.org as well as usingdotnetwithschema.org with the intent of exposing the hierarchy of schema.org via POCOs and providing options of generating those models as pre-generated Micro-Data view snippets that could be used with the razor view engine.  

When JSON-LD came to my attention as the evidently preferred way of expressing schema.org classes, properties, actions, etc my plans changed as I saw that its the suggested way of 1.) having web crawlers index site/web-service data and 2.) provide sophisticated useful options to yield better rendered views (Google has taken great strides in this -- i.e. Google Rich Snippets).  I also saw how things like email can be enhanced now using JSON-LD to add auto-magically generated content links within email messages themselves... ie GMail.  Cool stuff!!

Now, my goal is to provide a way to allow a .Net developer easily populate and render the POCO schema.org class models in any way they see fit... ie Microdata AND/OR JSON-LD.  I consider this as really the "core" of an initial offering.

Then I  want to take this one step further... which I alluded to in my first comment.  This is specifically a direct JSON-LD data and JSON-LD enhanced HTML code snippet generation website/web-service that would act somewhat as a web-resource for ANY third party website to provide pre-rendered SEO (JSON-LD enhanced) friendly content for inclusion into their own websites.  Something that 'any Joe' can use to have the tricky Microdata/JSON-LD stuff done for them and they just embed the specified content on-the-fly in their own webpages via AJAX,/JQuery direct RESTful calls from within script tags. using a templating engine like Handlebars or called within server-side rendering implementations.

Let me explain this a bit better... Imagine I built a publicly available multi-tenanted, secure, encrypted web-service; where numerous well-known "most common" schema.org representations of their data for specific things like users/products/events/etc. is securely stored in the cloud in some encrypted backing data store like Mongo, SQL Server or Redis,  Consider that the customers of this site/web-service utilize it as the primary data store for things that they would want represented in their website like products, people, events... you know, the exact stuff that Schema.org models. 

This wouldn't simply be another 'Shopify' kind of back-end but instead will be much broader; encompassing the scope of schema.org.

Customers in essence need to have their entity data managed and stored using familiar methods like a simple oAuth protected RESTful CRUD API, or also perhaps they wish to utilize corresponding easy-to-use forms to perform CRUD operations directly as well  (in case they don't want to use an API).  Each form would need to be templated as required to address all the properties of a comprehensive schema.org class models (ie: a set of individual products and their corresponding offers/variants of specific SKUs). 

There would be lots of different schema.org classes and their respective Microdata/JSON-LD representations included as "standard" entities to choose from as data-stores to cover the most popular schema.org @types used for various use-cases and industries.

I believe that naturally, these same customers also want an easy way to get the properly formatted HTML and JSON-LD back from this web-service so that all of their products etc would be greatly enhanced to take advantage of SEO features that would increase their sites' view-ability, information, statistics and more --directly benefiting in their inclusion in 'enhanced' presentation within crawler result pages such as Google, Bing, Yahoo, etc.  Google uses JSON-LD as reference examples for Structured Data SEO for their Knowledge Graph (companies and people).  There is a HUGE need for this!

As such the customer's websites could take advantage of things like Google's Rich Snippets that will leverage the JSON-LD data that the web-service yields. 

So, to sum it up,  I would like to provide a straight forward way for ANYONE to make RESTful API requests, routed by schema.org @type classes (i.e. individual-product), and get back either:

1. Raw populated JSON-LD objects of any specified schema.org POCO model (which they can then do whatever they want with like embed as a <script> link into their web pages

2.) Pre-built Microdata formatted HTML snippets of a laundry list of possible templated schema.org class @type models (and the properties)... this of coarse would include hierarchical embedded properties so the rendered Microdata enhance HTML might be 'quite complicated'.

I know that this was long-winded... but I hope it explains the general BIG idea a bit better.  I wouldn't mind partnering up with some other folks like yourself to provide this as starter project to be eventually folded into a real commercial venture.

**Comment by markchipman** [comment]
... got cut off :(

1. Raw populated JSON-LD objects of any specified schema.org POCO model (which they can then do whatever they want with like embed as a <script> link into their web pages

2.) Pre-built Microdata formatted HTML snippets of a laundry list of possible templated schema.org class @type models (and the properties)... this of coarse would include hierarchical embedded properties so the rendered Microdata HTML might be quite complicated.

I know that this was long-winded... but I hope it explains the general BIG idea a bit better.  I wouldn't mind partnering up with some other folks like yourself to provide this as starter project to be eventually folded into a real commercial venture.

**Comment by goofballLogic** [comment]
This library will now aim to be more-or-less equivalent to the JavaScript counterpart (https://github.com/digitalbazaar/jsonld.js/) which has become a pseudo-reference for implementations. An additional library to add POCO bindings might be a welcome addition.
