### ISSUE TITLE
Support for signing

### ISSUE THREAD

**Issue by sondreb** [linked-data-dotnet/json-ld.net#74]
Does this library support signing of JSON-LD documents? If it does, perhaps some instructions could be added to the repo, or if not supported, perhaps we could attempt to add this functionality?

Here is an example from the [JSON-LD Playground](https://json-ld.org/playground/) where a document is signed with a Bitcoin private key:

![image](https://user-images.githubusercontent.com/309938/90312441-c834fb00-df04-11ea-88ab-82d7c7ffbaa1.png)

**Comment by goofballLogic** [comment]
Hmm. Good question. I'll look into it. @asbjornu do you know? Also @sondreb is this part of the core JSON-LD spec?

**Comment by asbjornu** [comment]
I'm pretty sure it doesn't. As `@context` references `https://w3id.org/security/v1`, I think this is an extension we would have to add, perhaps through its own assembly? There seems to be a swath of specs coming out of the 
[W3C Credentials Community Group](https://www.w3.org/community/credentials/) according to their [roadmap](https://w3c-ccg.github.io/roadmap/), so I assume a natural expansion of this would be to add support for the forthcoming specs in due time as well.

Would you be up for championing this effort, @sondreb? We will of course facilitate a repository in the `linked-data-dotnet` organization for you.

**Comment by sondreb** [comment]
I need this functionality and I'll contribute as much as I can. I need a cross-platform (JS+C#) library to perform signing of JSON documents.

I'll start with a repo on my own account, I just need some directions on how to possibly build extensions for json-ld.net?

**Comment by sondreb** [comment]
I don't know if this is what is used on the playground, but it's a [JavaScript implementation](https://github.com/digitalbazaar/jsonld-signatures) of [Linked Data Signature](https://web-payments.org/specs/source/lds2015/), which has migrated into [Linked Data Proofs](https://w3c-ccg.github.io/ld-proofs/).

**Comment by sondreb** [comment]
The end goal would probably be an .NET implementation of vc.js: https://github.com/digitalbazaar/vc-js

vc.js uses "jsonld-signatures", so I'll start with that.

**Comment by asbjornu** [comment]
Sounds like a good start, @sondreb. As to how to extend json-ld.net, your idea is as good as mine as we haven't done any of those yet. Perhaps @tpluscode has an idea how to approach this?

**Comment by goofballLogic** [comment]
Yeah my vote would be to stick as closely as possible to https://github.com/digitalbazaar/vc-js.

**Comment by veikkoeeva** [comment]
Great to see this library moving!

I would like to offer more context to what @sondreb wrote from my perspective that is similar.

I started working with a similar thing to @sondreb: I wrote a parser for [DIDs](https://www.w3.org/TR/did-core/) to be able to parse DID documents reasonable well and to suss out potential problems, see at https://github.com/w3c/did-core/issues/416 -> https://github.com/veikkoeeva/DotDecentralized. As DIDs is simpler than VCs, this would be also a step towards that goal.

In my case I was/am more interested to get a reasonable class structure so I could implement the DID specific rules as listed in the specification. Some look like being JSON-LD specific processing "for JSON programmers that work on JSON" and others are DID specific. In my case I assumed parsing just in compacted form and implement whatever DID rules and JSON-LD specific rules using extension and other methods. This way I could use `System.Text.Json` converters while (de)serializing. It looks like this works for DID documents as far as one assumes one form, e.g. compacted, be used all the time, or expanded

I am not sure if is because of DID specification tries to cater to "plain JSON users" (not all languages have robust JSON-LD libraries) or if that's how DIDs are specific at the moment, but there are places where a type of something is told using a type parameter before and one can use that information to parse and process subsequent fields. If a JSON-LD process tries to be more than a "JSON-LD database in memory" this may be something to consider. It also looks like it would be possible to use `System.Text.Json` (de)serialization mechanism to write out or read the documents in any format as long as it is JSON (or when the library makes a pass, write to a side structure that can be whatever format). I used them to guarantee writing the structure in certain order (as `System.Text.Json` does not guarantee order)
